### ISSUE TITLE
Определить назначение проекта. Проанализировать предметную область.

### ISSUE THREAD

**Issue by kruglovaliza** [intensive3/project#3]

**Comment by SemyonTikhov** [comment]
Назначение проекта:
1.Показать людям при помощи технологий дополненной реальности какой памятник был месте памятника Ленину.
2.Увеличить интерес туристов и жителей Костромы к истории нашего города и страны.
 
Предметная область (задачи, работы, результаты):
Задача.
Разработать мобильное приложение для автоматизации гида, привлечения туристов и более эффективного изучения культуры.
Работы.
Создание приложения.
Создание 3D модели памятника в Blender или Unity.
Результаты.
Готовое приложение, которое может скачать любой желающий , сканируя QR Код. Наводя камеру на памятник Ленину пользователь будет видеть на его месте памятник 300-летию дома Романовых.
