### ISSUE TITLE
Сформулировать требования у проекту.

### ISSUE THREAD

**Issue by kruglovaliza** [intensive3/project#4]

**Comment by PolinaK1** [comment]
Требования к проекту

- Приложение должно запускаться на любых версиях мобильных операционных систем типа Android.  (Android 5.0 / 5.1 Lollipop и выше).

- Приложение должно адаптивно подстраиваться под различные разрешения экранов и плотности пикселей. 

- Дизайн приложения – простой и понятный для пользователя с элементами Flat.

- Работоспособность приложения камеры при включении (Для наведения на объект). 

- Рассмотреть различные поведения приложения – открытие встроенной системной камеры, либо в приложении.

- Адаптивный размер текста (В настройках должна быть функция увеличения / уменьшения размера текста).

- Визуальная подсказка в режиме камеры. Если объект не в поле зрения, то указателями по краям экрана подсказывать пользователю, в какой стороне объект. 

- Возможность оставлять отзывы и комментарии на памятник / объект. После отзыва и модерации – все остальные пользователи могут его увидеть и оценить.

- Наличие справки приложения. Пользователь при возникновении вопросов может прочитать отдельный блок справки. 

- Проработаны все ошибки в приложении. (С сообщениями для пользователя)

- Наличие аудио версии текста о памятнике. С возможностью регулировать скорость воспроизведения. 

- Возможность поэтапно смотреть исторические версии памятника, перемещение по экрану мобильного устройства. (Пользователь может выбрать один из этапов стройки, вращать в разные стороны 3D объект).

- Наличие кнопки “поделиться”. В Share message уже изначально должно быть сообщение с кратким описанием действия пользователя. (Пример: на стену в Вконтакте публикуется запись: “Всем привет, я побывал у памятника Ленину в Костроме *рез-т фото*, название приложения). 

- Корректная работа приложения при сворачивании. (Не должно полностью закрываться при переходе в другое / из другого).

- Наличие в настройках “Информации” – Политика использования данных, Условия использования, Библиотека с открытым исходным кодом)
