### ISSUE TITLE
Создать макет работы. (пользовательский сценарий)

### ISSUE THREAD

**Issue by kruglovaliza** [intensive3/project#5]

**Comment by katemless** [comment]
Пользователь открывает приложение, сканирует QR-код, расположенный около исторического объекта. Программа через камеру проецирует на окружающий ландшафт виртуальную модель памятника с возможностью прослушать или прочитать информацию о нем.

**Comment by katemless** [comment]
![Android - 1](https://user-images.githubusercontent.com/61832624/76437208-43303d80-63ca-11ea-83d0-5ea787de6407.jpg)
![Android - 2](https://user-images.githubusercontent.com/61832624/76437219-4a574b80-63ca-11ea-99ce-437af0075c55.jpg)
![Android - 3](https://user-images.githubusercontent.com/61832624/76437223-4c210f00-63ca-11ea-9017-78759ea14534.jpg)
![Android - 4](https://user-images.githubusercontent.com/61832624/76437227-4d523c00-63ca-11ea-8569-302c6d982721.jpg)
![Android - 5](https://user-images.githubusercontent.com/61832624/76437230-4f1bff80-63ca-11ea-85c0-facd08ecea40.jpg)
